local util = require("jitlog.util")
local format = string.format
local buildtemplate = util.buildtemplate

local generator = {
  outputlang = "lua",
  default_filename = "reader_def.lua",
  typerename = {
    bool = "bool"
  }
}

generator.templates = {
  comment_line = "-- %s",
  namelist = [[
local {{name}} = {
{{list:  "%s",\\n}}}

]],

  enum = [[
local {{name}} = util.make_enum{
{{list}}}
lib.{{name}} = {{name}}

]],
  enumline = '"%s",\n',
  msgsizes = [[local msgsizes = {
{{list:  %s\n}} };
lib.msgsizes = msgsizes

]],
  struct = [[
typedef struct {{name}}{
  {{fields}}
}__attribute__((packed)) {{name}};

]],
  msgstruct = [=[
  {{name}} = ffi.typeof([[
  struct { {{fields}}
  }__attribute__((packed))
]]),

]=],
  structfield = "\n  %s %s;",
  struct_comment = "// %s",

  msg_metatable = [[
do
  local {{name}} = {}

{{fields:%s}}

  local getters = {
{{getter_names:    %s\n}}  }

  local function {{name}}_indexer(self, key)
    local getter = getters[key]
    if getter then
      return (getter(self))
    else
      local value = {{name}}[key]
      if not value then
        error("Unknown field " .. key .. " in message type {{name}}")
      end
      return value
    end
  end
  
  local {{name}}_mt = {
    __index =  {{name}}_indexer,
    getters = getters,
    funcs = {{name}},
  }
  
  ffi.metatype({{listname}}.{{name}}, {{name}}_mt)
end

]],

  msg_getter = [[
  function {{msgname}}:get_{{name}}()
    assert(self, "Expected a '{{msgname}}' message as first parameter")
    return {{body}}
  end

]],

  msg_vgetter = [[
  function {{msgname}}:get_{{name}}()
    assert(self, "Expected a '{{msgname}}' message as first parameter")
    local array, size = get_fbarray(self, self.{{name}}_offset, {{offset}}, {{type}})
    return {{body}}
  end
]],

  msg_strgetter = [[
  function {{msgname}}:get_{{name}}()
    assert(self, "Expected a '{{msgname}}' message as first parameter")
    return (get_fbstring(self, self.{{name}}_offset, {{offset}}))
  end
]],

  vtable = [[
  {{name}} = { {{offsets}} },
]],
}

function generator:fmt_fieldget(def, f)
  return "self."..f.name
end

function generator:needs_accessor(struct, f)
  return f.vlen or f.bitfield or f.bitstorage ~= nil
end

function generator:fmt_accessor_def(struct, f, voffset) 
  local body
  local template = self.templates.msg_getter
  local tvalues = {
    msgname = struct.name,
    name = f.name,
    kind = f.kind,
    offset = f.offset,
    default = "false",
    type = "nil",
  }

  local ftype = self.types[f.type]
  tvalues.kind = tvalues.kind or ftype.kind

  if f.vlen then
    template = self.templates.msg_vgetter

    tvalues.type = '"char*"'

    if f.type == "string" then
      template = self.templates.msg_strgetter
    elseif f.type == "stringlist" then
      tvalues.default = "{}"
      body = format("(parse_strlist(array, size))", body)
    else
      local type = self.types[f.type]
      assert(type.kind == "array")

      local eletype = self.types[type.element_type]
      if eletype.kind == "struct" then
        template = self.templates.msg_vgetter_struct
        tvalues.type = type.element_type
      else
        tvalues.type = '"'..self.types[f.type].c..'"'
      end
      -- Add the buffer element count and element size as extra return values
      body = "array, size"
    end
  elseif f.bitfield or f.bitstorage then
    body = format("(band(rshift(%s, %d), 0x%x))", "self." .. f.bitstorage, f.bitofs, bit.lshift(1, f.bitsize)-1)
  else
    assert(body, "unhandled field accessor type")
  end

  if f.bool then
    body = body .. " ~= 0"
  end

  tvalues.body = body
  -- Prevent a tail call be generated by wrapping the body in parentheses
  return buildtemplate(template, tvalues)
end

function generator:fmt_accessor_get(struct, f, msgvar)
  return format("%s:get_%s()", msgvar, f.name)
end

function generator:fmt_namelookup(enum, idvar)
  return format("%s_names[%s]", enum, idvar)
end


function generator:write_structlist(list, name, getters, names)
  self:writef("local %s = {\n", name)

  for _, def in ipairs(list) do
    if names then
      table.insert(names, def.name)
    end
    local field_getters = self:write_struct(def, self.templates.msgstruct)
    if field_getters then
      getters[def.name] = field_getters
    end
  end

  self:writeline("}")
  self:writef("lib.%s = %s\n", name, name)
end

function generator:writefile(options)
  self:write([=[
local util = require("jitlog.util")
local ffi = require("ffi")
local ffi_cast, ffi_string = ffi.cast, ffi.string
local fb = require("jitlog.flatbuffers")
local parse_strlist = fb.parse_strlist
local band, rshift = bit.band, bit.rshift
local get_fbarray, get_fbstring = util.get_fbarray, util.get_fbstring

local lib = {}

local function getarray_count(msg, offset, adjustment)
  local array = msg + (adjustment or 0) + offset
  return ffi_cast("uint32_t*", array)[0]
end

local function nop() end

]=])
  self:write_enum("MsgType", self.sorted_msgnames)
  self:write_msgsizes(false)

  if GC64 then
    self:write([[

lib.GC64 = true

ffi.cdef("typedef uint64_t GCRef, MRef, GCSize;")]])
  else
    self:write([[

lib.GC64 = false

ffi.cdef("typedef uint32_t GCRef, MRef, GCSize;")]])
  end

  self:write("\n\n")

  local struct_getters = {}
  self:write_structlist(self.msglist, "messages", struct_getters)

  -- Add runtime validation that
  for _, def in ipairs(self.msglist) do
    self:writef("assert(ffi.sizeof(messages.%s) == %d)\n", def.name, def.size)
  end
  self:writeline()

  for i, list in ipairs({self.msglist}) do
    local listname = "messages"

    for _, def in ipairs(list) do
      local funclist = struct_getters[def.name]
      local getters = {}
      if not funclist then
        funclist = {}
      else
        -- Build a table of properties names to getter functions used by the indexer
        for _, f in ipairs(def.fields) do
          if self:needs_accessor(def, f) and (not f.vlen or f.type == "string" or f.type == "stringlist") then
            table.insert(getters, format("%s = %s.get_%s,", f.name, def.name, f.name))
          end
        end
      end

      local values = {
        name = def.name,
        msgdef = def,
        fields = funclist,
        getter_names = getters,
        listname = listname,
      }

      self:writetemplate("msg_metatable", values)
    end
  end

  self:write([[
  function lib.gen_msgparsers()
    local parsers = {}
    for i = 1, MsgType.MAX do
      local name = MsgType.names[i]
      local type = ffi.typeof("$ *", messages[name])
      parsers[name] = function(ptr) return (ffi_cast(type, ptr)) end
    end
    return parsers
  end
return lib
]])
end

return generator
